server:
  port: 9191
spring:
  h2:
    console:
      enabled: true
  application:
    name: PAYMENT-SERVICE
logging:
  file:
    name: /Users/sunjingsong/learning-center/javatechie/log/microservice.log